<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Namaa.Application\Namaa.Application.csproj" />
    <ProjectReference Include="..\Namaa.Infrastructure\Namaa.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>Namaa.Api</AssemblyName>
    <RootNamespace>Namaa.Api</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3058b4ec-2f7f-4e1c-b506-c4eef68fe15a</UserSecretsId>
  </PropertyGroup>

</Project>
